name: Sync Latest Xray Binaries

on:
  schedule:
    - cron: '0 9 1 * *' 
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab

permissions:
  contents: write # Needed for creating/updating GitHub releases

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Create Temp Distribution Directory
        run: |
          mkdir -p "${RUNNER_TEMP}/bin_dist" "${RUNNER_TEMP}/xray_extract_amd64" "${RUNNER_TEMP}/xray_extract_arm64"

      - name: Download and Extract AMD64 (x86_64) Binary
        run: |
          wget -q https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip -o Xray-linux-64.zip -d "${RUNNER_TEMP}/xray_extract_amd64"
          cp "${RUNNER_TEMP}/xray_extract_amd64"/xray "${RUNNER_TEMP}/bin_dist"/xray_amd64
          cp "${RUNNER_TEMP}/xray_extract_amd64"/geoip.dat "${RUNNER_TEMP}/bin_dist"/geoip.dat
          cp "${RUNNER_TEMP}/xray_extract_amd64"/geosite.dat "${RUNNER_TEMP}/bin_dist"/geosite.dat

      - name: Download and Extract ARM64 (aarch64) Binary
        run: |
          wget -q https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-arm64-v8a.zip 
          unzip -o Xray-linux-arm64-v8a.zip -d "${RUNNER_TEMP}/xray_extract_arm64"
          cp "${RUNNER_TEMP}/xray_extract_arm64"/xray "${RUNNER_TEMP}/bin_dist"/xray_arm64

      - name: Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Xray Binaries
          body: "Automatic sync with latest Xray-core release."
          files: |
            ${{ runner.temp }}/bin_dist/xray*
            ${{ runner.temp }}/bin_dist/geo*.dat
            
          fail_on_unmatched_files: true
          make_latest: true
